package art.arcane.witchery.registry;

import java.util.List;

public final class LegacyRegistryData {
    private LegacyRegistryData() {
    }

    public static final List<String> BLOCKS = List.of(
        "belladonna",
        "mandrake",
        "artichoke",
        "snowbell",
        "wormwood",
        "mindrake",
        "wolfsbane",
        "garlicplant",
        "witchsapling",
        "witchlog",
        "witchleaves",
        "voidbramble",
        "bramble",
        "glintweed",
        "spanishmoss",
        "leapinglily",
        "plantmine",
        "embermoss",
        "crittersnare",
        "grassper",
        "bloodrose",
        "somniancotton",
        "web",
        "vine",
        "cactus",
        "lilypad",
        "demonheart",
        "wolfhead",
        "witchwood",
        "stairswoodrowan",
        "stairswoodalder",
        "stairswoodhawthorn",
        "witchwoodslab",
        "witchwooddoubleslab",
        "rowanwooddoor",
        "alderwooddoor",
        "chalice",
        "candelabra",
        "placeditem",
        "alluringskull",
        "wickerbundle",
        "glowglobe",
        "statuegoddess",
        "stockade",
        "icestockade",
        "perpetualice",
        "icedoor",
        "icestairs",
        "iceslab",
        "icedoubleslab",
        "icefence",
        "icefencegate",
        "icepressureplate",
        "snowpressureplate",
        "snowstairs",
        "snowslab",
        "snowdoubleslab",
        "infinityegg",
        "slurp",
        "pitdirt",
        "pitgrass",
        "garlicgarland",
        "bloodedwool",
        "shadedglass",
        "shadedglass_active",
        "mirrorwall",
        "refillingchest",
        "force",
        "tormentstone",
        "barrier",
        "leechchest",
        "altar",
        "kettle",
        "poppetshelf",
        "dreamcatcher",
        "crystalball",
        "spiritportal",
        "tormentportal",
        "spinningwheel",
        "brazier",
        "witchesovenidle",
        "witchesovenburning",
        "fumefunnel",
        "filteredfumefunnel",
        "distilleryidle",
        "distilleryburning",
        "scarecrow",
        "trent",
        "witchsladder",
        "decurseteleport",
        "decursedirected",
        "statueofworship",
        "cauldron",
        "wolfaltar",
        "silvervat",
        "beartrap",
        "wolftrap",
        "wallgen",
        "coffinblock",
        "light",
        "daylightcollector",
        "bloodcrucible",
        "mirrorblock",
        "mirrorblock2",
        "circle",
        "circleglyphritual",
        "circleglyphotherwhere",
        "circleglyphinfernal",
        "spiritflowing",
        "hollowtears",
        "disease",
        "brew",
        "brewgas",
        "brewliquid",
        "clever",
        "cwoodendoor",
        "cwoodpressureplate",
        "cstonepressureplate",
        "csnowpressureplate",
        "cbuttonwood",
        "cbuttonstone"
    );

    public static final List<String> ITEMS = List.of(
        "ingredient",
        "taglockkit",
        "poppet",
        "potion",
        "witchwoodslab",
        "witchwooddoubleslab",
        "iceslab",
        "icedoubleslab",
        "snowslab",
        "snowdoubleslab",
        "coffin",
        "stew",
        "stewraw",
        "mirror",
        "chalkritual",
        "chalkotherwhere",
        "chalkinfernal",
        "chalkheart",
        "boline",
        "arthana",
        "huntsmanspear",
        "handbow",
        "deathshand",
        "silversword",
        "canesword",
        "witchhand",
        "circletalisman",
        "mysticbranch",
        "divinerwater",
        "divinerlava",
        "polynesiacharm",
        "devilstonguecharm",
        "mutator",
        "louse",
        "brewbag",
        "spectralstone",
        "shelfcompass",
        "kobolditepickaxe",
        "dupstaff",
        "brewbottle",
        "brew.fuel",
        "brew.water",
        "bookbiomes2",
        "biomenote",
        "cauldronbook",
        "leonardsurn",
        "playercompass",
        "mooncharm",
        "hornofthehunt",
        "wolftoken",
        "glassgoblet",
        "sungrenade",
        "vampirebook",
        "dupgrenade",
        "witchhat",
        "babashat",
        "witchrobe",
        "necromancerrobe",
        "bitingbelt",
        "barkbelt",
        "iceslippers",
        "rubyslippers",
        "seepingshoes",
        "hunterhat",
        "huntercoat",
        "hunterlegs",
        "hunterboots",
        "hunterhatsilvered",
        "huntercoatsilvered",
        "hunterlegssilvered",
        "hunterbootssilvered",
        "hunterhatgarlicked",
        "huntercoatgarlicked",
        "hunterlegsgarlicked",
        "hunterbootsgarlicked",
        "deathscowl",
        "deathsrobe",
        "deathsfeet",
        "quiverofmog",
        "gurdleofgulg",
        "kobolditehelm",
        "earmuffs",
        "vampirehat",
        "vampirehelmet",
        "vampirecoat",
        "vampirecoat_female",
        "vampirechaincoat",
        "vampirechaincoat_female",
        "vampirelegs",
        "vampirelegs_kilt",
        "vampireboots",
        "seedsbelladonna",
        "seedsmandrake",
        "seedsartichoke",
        "seedssnowbell",
        "seedswormwood",
        "seedsmindrake",
        "seedswolfsbane",
        "garlic",
        "bucketspirit",
        "buckethollowtears",
        "bucketbrew"
    );

    public static final List<String> FLUIDS = List.of(
        "fluidspirit",
        "hollowtears",
        "brew",
        "brewgas",
        "brewliquid",
        "fluiddisease"
    );

    public static final List<String> ENTITIES = List.of(
        "demon",
        "broom",
        "brew",
        "familiar",
        "mandrake",
        "treefyd",
        "hornedHuntsman",
        "spellEffect",
        "ent",
        "illusionCreeper",
        "illusionSpider",
        "illusionZombie",
        "owl",
        "toad",
        "cat",
        "louse",
        "eye",
        "babayaga",
        "covenwitch",
        "corpse",
        "nightmare",
        "spectre",
        "poltergeist",
        "banshee",
        "spirit",
        "death",
        "bolt",
        "witchhunter",
        "deathhorse",
        "lordoftorment",
        "soulfire",
        "imp",
        "darkmark",
        "mindrake",
        "goblin",
        "goblinmog",
        "goblingulg",
        "brew2",
        "item",
        "droplet",
        "splatter",
        "leonard",
        "lostsoul",
        "wolfman",
        "hellhound",
        "werevillager",
        "villageguard",
        "vampire",
        "grenade",
        "lilith",
        "follower",
        "wingedmonkey",
        "attackbat",
        "mirrorface",
        "reflection"
    );

    public static final List<LegacyPacketIntent> PACKETS = List.of(
            new LegacyPacketIntent(1, "brew_prepared", PacketFlow.SERVERBOUND),
            new LegacyPacketIntent(2, "particles", PacketFlow.CLIENTBOUND),
            new LegacyPacketIntent(3, "cam_pos", PacketFlow.CLIENTBOUND),
            new LegacyPacketIntent(4, "item_update", PacketFlow.SERVERBOUND),
            new LegacyPacketIntent(5, "player_style", PacketFlow.CLIENTBOUND),
            new LegacyPacketIntent(6, "player_sync", PacketFlow.CLIENTBOUND),
            new LegacyPacketIntent(7, "push_target", PacketFlow.CLIENTBOUND),
            new LegacyPacketIntent(8, "sound", PacketFlow.CLIENTBOUND),
            new LegacyPacketIntent(9, "spell_prepared", PacketFlow.SERVERBOUND),
            new LegacyPacketIntent(10, "clear_fall_damage", PacketFlow.SERVERBOUND),
            new LegacyPacketIntent(11, "sync_entity_size", PacketFlow.CLIENTBOUND),
            new LegacyPacketIntent(12, "sync_markup_book", PacketFlow.SERVERBOUND),
            new LegacyPacketIntent(13, "extended_player_sync", PacketFlow.CLIENTBOUND),
            new LegacyPacketIntent(14, "howl", PacketFlow.SERVERBOUND),
            new LegacyPacketIntent(15, "extended_villager_sync", PacketFlow.CLIENTBOUND),
            new LegacyPacketIntent(16, "select_player_ability", PacketFlow.SERVERBOUND),
            new LegacyPacketIntent(17, "extended_entity_request_sync_to_client", PacketFlow.SERVERBOUND),
            new LegacyPacketIntent(18, "partial_extended_player_sync", PacketFlow.CLIENTBOUND),
            new LegacyPacketIntent(19, "set_client_player_facing", PacketFlow.CLIENTBOUND)
    );

    public static final List<String> EFFECTS = List.of(
        "potion.paralysed",
        "potion.wrappedinvine",
        "potion.spiked",
        "potion.sprouting",
        "potion.grotesque",
        "potion.love",
        "potion.allergysun",
        "potion.chilled",
        "potion.snowtrail",
        "potion.floating",
        "potion.hellishaura",
        "potion.brewingexpertise",
        "potion.doublejump",
        "potion.featherfall",
        "potion.allergydark",
        "potion.reincarnate",
        "potion.insane",
        "potion.keepinventory",
        "potion.sinking",
        "potion.overheating",
        "potion.wakingnightmare",
        "potion.queasy",
        "potion.swimming",
        "potion.resizing",
        "potion.colorful",
        "potion.enderinhibition",
        "potion.illfitting",
        "potion.volatility",
        "potion.enslaved",
        "potion.mortalcoil",
        "potion.absorbmagic",
        "potion.poisonweapons",
        "potion.reflectprojectiles",
        "potion.reflectdamage",
        "potion.attractprojectiles",
        "potion.repellattacker",
        "potion.stoutbelly",
        "potion.feelnopain",
        "potion.gasmask",
        "potion.diseased",
        "potion.fortune",
        "potion.worship",
        "potion.keepeffects",
        "potion.wolfsbane"
    );

    public static final List<LegacyMenuIntent> MENUS = List.of(
            new LegacyMenuIntent(0, "altar"),
            new LegacyMenuIntent(1, "witchcraft_book"),
            new LegacyMenuIntent(2, "witches_oven"),
            new LegacyMenuIntent(3, "distillery"),
            new LegacyMenuIntent(4, "spinning_wheel"),
            new LegacyMenuIntent(5, "brew_bag"),
            new LegacyMenuIntent(6, "biome_book"),
            new LegacyMenuIntent(7, "markup_book"),
            new LegacyMenuIntent(8, "leonards_urn")
    );

    public static final List<String> BLOCK_ENTITIES = List.of(
        "alluringskull",
        "altar",
        "barrier",
        "beartrap",
        "bloodcrucible",
        "bloodrose",
        "brazier",
        "brewgas",
        "brewliquid",
        "candelabra",
        "cauldron",
        "chalice",
        "circle",
        "cbuttonstone",
        "cbuttonwood",
        "clever",
        "coffinblock",
        "crystalball",
        "csnowpressureplate",
        "cstonepressureplate",
        "cwoodendoor",
        "cwoodpressureplate",
        "decursedirected",
        "decurseteleport",
        "demonheart",
        "distilleryburning",
        "distilleryidle",
        "dreamcatcher",
        "filteredfumefunnel",
        "fumefunnel",
        "garlicgarland",
        "grassper",
        "kettle",
        "leechchest",
        "mirrorblock",
        "mirrorblock2",
        "placeditem",
        "poppetshelf",
        "refillingchest",
        "scarecrow",
        "silvervat",
        "slurp",
        "spinningwheel",
        "statuegoddess",
        "statueofworship",
        "trent",
        "voidbramble",
        "wallgen",
        "witchesovenburning",
        "witchesovenidle",
        "witchsladder",
        "wolfaltar",
        "wolfhead",
        "wolftrap"
    );

    public enum PacketFlow {
        CLIENTBOUND,
        SERVERBOUND
    }

    public record LegacyPacketIntent(int legacyId, String key, PacketFlow flow) {
    }

    public record LegacyMenuIntent(int legacyGuiId, String key) {
    }
}
